services:
  web:
    build: .
    container_name: form_engine_api
    ports:
      - "8000:8000"
    env_file:
      - .env                   
    depends_on:
      - db
      - redis

  db:
    image: postgres:16-alpine
    container_name: form_engine_postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: form_engine_redis
    ports:
      - "6379:6379"

volumes:
  postgres_data: